name: Bug report
description: 创建一个关于此项目的 Bug 报告
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Bug 描述

        请简要描述 bug 的性质。

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 复现步骤
      description: 请详细描述如何复现该 bug 的步骤。
      placeholder: |
        1. 打开 xxx 页面
        2. 点击 yyy 按钮
        3. 滚动到 zzz 部分
        4. 看到错误

  - type: textarea
    id: expected_behavior
    attributes:
      label: 预期行为
      description: 请描述在没有 bug 的情况下你期望看到的结果。

  - type: textarea
    id: actual_behavior
    attributes:
      label: 实际行为
      description: 请描述在 bug 出现时实际看到的结果。

  - type: input
    id: screenshots
    attributes:
      label: 截图
      description: 如果适用，请添加截图以帮助解释你的问题。

  - type: textarea
    id: environment
    attributes:
      label: 环境
      description: 请提供以下信息：
      placeholder: |
        - 操作系统：Windows 10 / macOS Catalina / Ubuntu 20.04
        - 浏览器：Chrome 91 / Firefox 89 / Safari 14
        - 应用版本：[例如 v1.2.3]
        - 其他相关信息：

  - type: textarea
    id: additional_info
    attributes:
      label: 其他信息
      description: 如果你有其他认为有助于解决此问题的信息，请在这里提供。
