blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: "Bug report (Markdown)"
    description: "使用 Markdown 文件的 Bug 报告模板"
    title: "[BUG] "
    labels: ["bug"]
    assignees: []
    file: "bug_report.md"
  - name: "Bug report (YAML)"
    description: "使用 YAML 文件的 Bug 报告模板"
    title: "[BUG] "
    labels: ["bug"]
    assignees: []
    file: "bug_report.yml"
