name: Update User Script Versions

on:
  schedule:
    - cron: '0 0 */2 * *'  # 每两天午夜12点 UTC 时间运行一次
  push:
    branches:
      - main

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # 使用你创建的 Token

      - name: Read file list
        run: |
          # 查看文件列表内容
          cat files.txt
          
      - name: Extract current version
        id: extract_version
        run: |
          while IFS= read -r file; do
            echo "Processing file: \"$file\""
            if [ -f "$file" ]; then
              current_version=$(awk '/^\/\/ @version/ {print $NF}' "$file")
              echo "Current version for $file: $current_version"
              
              if [ -z "$current_version" ]; then
                echo "Version number not found in the script file: $file"
                exit 1
              fi
