name: 更新用户脚本版本

on:
  schedule:
    - cron: '0 0 * * *'  # 每天的 UTC 时间 0 点，即中国时间的早上 8 点
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 检出代码
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # 使用你创建的 Token

      - name: 获取当前分支
        id: get_branch
        run: |
          echo "当前分支: $(git rev-parse --abbrev-ref HEAD)"
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: 拉取最新更改
        run: |
          git pull origin ${{ env.branch }}  # 拉取最新的远程更改

      - name: 调试文件列表
        run: |
          echo "当前脚本路径列表:"
          cat docs/ScriptsPath.txt  # 打印 docs/ScriptsPath.txt 文件内容以进行调试

      - name: 提取当前版本
        id: extract_version
        run: |
          while IFS= read -r file; do
            echo "处理文件: \"$file\""
            if [ -f "$file" ]; then
              current_version=$(awk '/^\/\/ @version/ {print $NF}' "$file")
              echo "文件 $file 的当前版本: $current_version"
              
              if [ -z "$current_version" ]; then
                echo "在脚本文件 $file 中未找到版本号"
                exit 1
              fi
              
              # 将版本号中的.替换为空格，以便进行加法操作
              version_number=$(echo "$current_version" | sed 's/\./ /g')
              echo "版本号（转换为数字）: $version_number"
              
              # 将版本号转换为数字并加1
              version_number=$(echo $version_number | awk '{printf "%d", ($1*1000000 + $2*10000 + $3*100 + $4 + 1)}')
              echo "版本号（加1后的数字）: $version_number"
              
              # 还原为4部分版本号，并分割为数组
              major=$((version_number / 1000000))
              minor=$(( (version_number % 1000000) / 10000 ))
              patch=$(( (version_number % 10000) / 100 ))
              build=$(( version_number % 100 ))
              
              # 生成新的版本号
              new_version="$major.$minor.$patch.$build"
              echo "文件 $file 的新版本号: $new_version"
              
              # 替换版本号
              sed -i "s|// @version[ ]\+[0-9]*\([.][0-9]*\)*|// @version $new_version|" "$file"
              
              # 将新的版本号添加到环境变量中
              echo "${file}_NEW_VERSION=$new_version" >> $GITHUB_ENV
            else
              echo "未找到脚本文件: $file"
              exit 1
            fi
          done < docs/ScriptsPath.txt

      - name: 检查 @version 是否已更新
        run: |
          while IFS= read -r file; do
            echo "检查文件中的版本号: $file"
            grep '^// @version' "$file"
          done < docs/ScriptsPath.txt

      - name: 调试环境变量
        run: |
          echo "当前环境变量:"
          cat $GITHUB_ENV  # 打印环境变量以进行调试

      - name: 调试更改
        run: |
          echo "Git 状态:"
          git status
          echo "更改的差异:"
          git diff  # 打印更改的差异以进行调试

      - name: 提交和推送更改
        run: |
          # 配置 Git 用户
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 将更改添加到 Git 中
          git add .
          
          # 提交更改
          commit_message="更新版本号"
          echo "提交信息: $commit_message"
          git commit -m "$commit_message" || echo "没有需要提交的更改"
          
          # 推送更改
          git push origin ${{ env.branch }}  # 推送到当前分支
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # 传递 Token 到 Git 环境变量中
