name: 翻译自述文件
on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  translate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install googletrans==4.0.0-rc1

      - name: 获取当前分支
        id: get_branch
        run: |
          echo "当前分支: $(git rev-parse --abbrev-ref HEAD)"
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: 拉取远程更新
        run: |
          git fetch origin ${{ env.branch }}

      - name: 检查文件状态并更新 translate_readme.json
        run: |
          python compare_readme.py
          git add docs/translate_readme.json
          git commit -m "临时提交本地更改" || echo "没有需要提交的更改"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: 创建临时备份文件
        run: |
          echo "{}" > /tmp/translate_readme_backup.json
          cp docs/translate_readme.json /tmp/translate_readme_backup.json

      - name: 拉取最新更改
        run: |
          git pull origin ${{ env.branch }}

      - name: 恢复暂存的本地更改
        run: |
          cp /tmp/translate_readme_backup.json docs/translate_readme.json

      - name: 读取并翻译 README 文件
        run: |
          python translate_readme.py  # 确保这个脚本实际进行了更改
        continue-on-error: true

      - name: 提交和推送更改
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add .
          git commit -m '自动谷歌翻译 README 文件' || echo "没有需要提交的更改"
          git push origin ${{ env.branch }}
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
